### ISSUE TITLE
bin/deploy should update the version of git-lfs installed

### ISSUE THREAD

**Issue by heather999** [lsst/lsstsw#107]
Currently, bin/deploy installs git-lfs 1.0.2. This is rather old and does not include the more recent feature modification which is referenced in the DM Doc, namely "git lfs install":
http://developer.lsst.io/en/latest/tools/git_lfs.html
See: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3779 
Further it seems the current DM configuration instructions do not work at all for git-lfs 1.0.2.  Once I upgraded to 1.2.0 things were working in accordance to the DM documentation.  
Would it be possible to upgrade the version of git-lfs that ./bin/deploy installs so others do not run into similar problems?

**Comment by jdswinbank** [comment]
Added to JIRA as [DM-6110](https://jira.lsstcorp.org/browse/DM-6110).

**Comment by heather999** [comment]
Thanks - next time I'll use JIRA - I've apparently become overly GItHub-happy :P

**Comment by jdswinbank** [comment]
DM-6110 is now done. This should be included in the next (v12.0) release of the stack.
