### ISSUE TITLE
Permissions in build directory are tricky for shared lsstsw installations

### ISSUE THREAD

**Issue by danielsf** [lsst/lsstsw#175]
We (LSST Sims) have a shared installation of lsstsw.  Earlier this morning, user A tried to build something on it, but it failed on the package ephem.  Some time later, user B tried to run `rebuild`.  While cloning ephem, lsstsw failed because it did not have permission to clean out the files in `build/ephem/`.  User B ran `ls -l` and, indeed, those files were owned by user A with permissions set to `-rw-r-----`.

Is there a reason lsstsw clones things with such restrictive permissions?  Would it be possible to change it so that, on shared lsstsw installations, members of the owners group can delete files from the `build/` directory in the case of an aborted `rebuild`?

**Comment by jhoblitt** [comment]
That is git's default behavior.  You could try setting either `core.sharedRepository` or `umask` in `~/.gitconfig` but I have personally never used those settings.
