### ISSUE TITLE
question about pandas/h5py and missing tables module

### ISSUE THREAD

**Issue by johannct** [lsst/lsstsw#231]
conda3_packages-linux-64.txt does not list h5py as a required module, but somehow it is pulled in it seems. But then one has pandas and  h5py in the stack python ecosystem, without being able to use hdf5 output from pandas, because the package tables is missing. Any chance to fix this one way or another?

**Comment by johannct** [comment]
sorry, I missed it. Will do, thanks

**Comment by wmwv** [comment]
Hmmm... This confusion is from me.  I followed

https://pipelines.lsst.io/install/lsstsw.html

to point @johannct to

https://github.com/lsst/lsstsw/blob/10a4fa6/etc/conda3_packages-linux-64.txt
(which does not list `h5py` or `hdf5`)

But thanks to @jhoblitt I realize that the above link is out of date and instead should point to master:
https://github.com/lsst/lsstsw/blob/master/etc/conda3_packages-linux-64.txt
(which does list `h5py` and `hdf5`)

**Comment by wmwv** [comment]
PR to update pipelines.lsst.io submitted as:

https://github.com/lsst/pipelines_lsst_io/pull/108
